server:
  port: 9090
  ip: 101.132.170.160
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/halo?serverTimezone=GMT%2b8
      username: root
      password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


files:
  upload:
     path: D:/Download/temp/
     #path: /home/files/
